### POST Post
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydXZMb1FXWnNBZU1oNVJnOFdTQ3N1MjdxOHciLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDM0OTI2NzQsImZ2YSI6WzMzNDksLTFdLCJpYXQiOjE3NDM0OTI2MTQsImlzcyI6Imh0dHBzOi8vbW92aW5nLXJhY2VyLTc0LmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc0MzQ5MjYwNCwic2lkIjoic2Vzc18ydjBvellzQlF3ZEJvNnZHTkhacGxJeXB6OVciLCJzdWIiOiJ1c2VyXzJ2MG96ZzkxM0JsdkRQZnQxb0F2NnhkZHAySCJ9.IQNZPFXjPjWXTvta5Fr3fwSLVxYGsymAYun2XIBzK6busV9ID94LcNxHGAmaa7Zf_BUusBnkvLErxf4X20eA0RnUNcLbqiqyC-pTf1vQ9mr3rXdkoFSUDRsAO_ZcLJdbGFdVKC4259rTy0RCcMe8DrSbmwGme6EpIBzMsWGVhNZeAqU9Sp99KgR9WHkzBbHNKeABN8shlvCJ7xrAs6jhGAaSfc5i7Bw47cdmKzWob3lzV3upxa1axmzJTFdLjc1ECRAgpPob6xbBS9vWwFRnUWMSgCfIKqobKwZ0Wi85ETl274IekrDiBKyvNrELf0qOPBBfgdmiO__DeYMZYjj5bw


{
  "title": "Title from Postman",
  "slug": "slug-from-postman4",
  "content": "Content from POSTMAN"
}
